# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - name: Python environment
      run: |
        export PATH=`which pylint':$PATH
        make setup
    - name: Install dependencies
      run: |
        make install
    - name: Linting
      run: |
        sudo make lint
    - name: Test with pytest
      run: |
        make test
